package:
  name:    {{ name }}
  version: {{ version }}

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"


build:
  number: 0
  noarch: python
  entry_points:
    - ncbi_sequences = ncbi_db:run_ncbi_sequences
    - ncbi_assembly = ncbi_db:run_ncbi_assembly
    - ncbi_pubmed = ncbi_db:run_ncbi_pubmed
    - ncbi_search = ncbi_db:run_ncbi_search
    - ncbi_taxonomy = ncbi_db:run_ncbi_taxonomy
    - ncbi_taxonomy_tree = ncbi_db:run_ncbi_taxonomy_tree
    - parse_genbank = ncbi_db:run_parse_genbank

  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - biopython
    - ete3
    - lxml
    - six
    - easyterm

about:
  home: "https://github.com/marco-mariotti/{{ name }}"
  license: MIT
  license_family: MIT
  license_file:
  summary: "Utilities to query and download NCBI data"
  doc_url:
  dev_url:

extra:
  recipe-maintainers:
    - marco-mariotti
